# Generated by Django 3.2.5 on 2021-08-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='name',
            field=models.CharField(max_length=50, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.IntegerField(verbose_name='価格'),
        ),
    ]
